namespace: upcloud
name: cloud
version: 0.8.1
readme: README.md
authors:
  - UpCloud developers (github.com/UpCloudLtd)
description: A collection for managing UpCloud resources & inventory
license_file: 'LICENSE'
tags:
  - upcloud
  - cloud

repository: https://github.com/UpCloudLtd/upcloud-ansible-collection
documentation: https://github.com/UpCloudLtd/upcloud-ansible-collection
homepage: https://github.com/UpCloudLtd/upcloud-ansible-collection
issues: https://github.com/UpCloudLtd/upcloud-ansible-collection/issues
