namespace: community
name: upcloud
version: 0.1.0
readme: README.md
authors:
  - UpCloud developers (github.com/UpCloudLtd)
description: A collection for managing UpCloud resources & inventory
license: MIT
license_file: 'LICENSE'
tags:
  - upcloud
  - cloud

repository: https://github.com/UpCloudLtd/upcloud-ansible-collection
documentation: TODO
homepage: https://github.com/UpCloudLtd/upcloud-ansible-collection
issues: https://github.com/UpCloudLtd/upcloud-ansible-collection/issues
